In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('fifa_22.csv', sep = '\;')   # 구분자 ; 
data = data.drop('player_id', axis = 1)

In [3]:
print(data.shape)
data.head(30)    # nationality에 "", '' 등 불필요한 문자 있음

(18000, 7)


name  nationality   position  overall  age  potential  \
0             Lionel Messi    Argentina   ST,CF,RW       93   34         93   
1       Robert Lewandowski       Poland         ST       92   33         92   
2            Kylian Mbappé       France      ST,LW       91   22         95   
3                Jan Oblak     Slovenia         GK       91   28         93   
4          Kevin De Bruyne       elgium     CM,CAM       91   30         91   
5                Neymar Jr       Brazil     CAM,LW       91   29         91   
6        Cristiano Ronaldo     Portugal      ST,LW       91   36         91   
7               Harry Kane      England         ST       90   28         90   
8     Gianluigi Donnarumma        Italy         GK       89   22         93   
9                  Alisson       Brazil         GK       89   28         90   
10          Joshua Kimmich      Germany     RB,CDM       89   26         90   
11                 Ederson       Brazil         GK       89   28         91   
12              Sadio Mané  """Senegal"         LW       89   29         89   
13         Virgil van Dijk  Netherlands         CB       89   30         89   
14                Casemiro       Brazil        CDM       89   29         89   
15        Thibaut Courtois       elgium         GK       89   29         91   
16          Erling Haaland       Norway         ST       88   21         93   
17         Bruno Fernandes     Portugal        CAM       88   27         89   
18         Raheem Sterling      England      RW,LW       88   26         89   
19            Keylor Navas   Costa Rica         GK       88   34         88   
20           Romelu Lukaku       elgium         ST       88   28         88   
21             Luis Suárez      Uruguay         ST       88   34         88   
22            Sergio Ramos        Spain         CB       88   35         88   
23              Rúben Dias     Portugal         CB       87   24         91   
24            Jadon Sancho      England   RM,LM,CF       87   21         91   
25  Trent Alexander-Arnold      England         RB       87   22         92   
26         Frenkie de Jong  Netherlands  CB,CDM,CM       87   24         92   
27        Andrew Robertson     Scotland         LB       87   27         88   
28            Paulo Dybala    Argentina     CAM,CF       87   27         88   
29              Marquinhos       Brazil     CB,CDM       87   27         90   

                   team  
0   Paris Saint-Germain  
1        Bayern München  
2   Paris Saint-Germain  
3    Atlético de Madrid  
4       Manchester City  
5   Paris Saint-Germain  
6     Manchester United  
7     Tottenham Hotspur  
8   Paris Saint-Germain  
9             Liverpool  
10       Bayern München  
11      Manchester City  
12            Liverpool  
13            Liverpool  
14          Real Madrid  
15          Real Madrid  
16    Borussia Dortmund  
17    Manchester United  
18      Manchester City  
19  Paris Saint-Germain  
20              Chelsea  
21   Atlético de Madrid  
22  Paris Saint-Germain  
23      Manchester City  
24    Manchester United  
25            Liverpool  
26         FC Barcelona  
27            Liverpool  
28             Juventus  
29  Paris Saint-Germain

In [4]:
data.nationality

0                  Argentina
1                     Poland
2                     France
3                   Slovenia
4                     elgium
                ...         
17995                 Norway
17996          """Australia"
17997       """Saudi Arabia"
17998    Republic of Ireland
17999                 Sweden
Name: nationality, Length: 18000, dtype: object

In [5]:
# 정규표현식으로 날림
data['nationality'] = data['nationality'].str.replace(pat=r'[^A-Za-z0-9]', repl= r' ', regex=True)
data['nationality'] = data['nationality'].str.replace(pat=r'[\s\s+]', repl= r' ', regex=True)

In [6]:
data

name          nationality  position  overall  age  \
0            Lionel Messi            Argentina  ST,CF,RW       93   34   
1      Robert Lewandowski               Poland        ST       92   33   
2           Kylian Mbappé               France     ST,LW       91   22   
3               Jan Oblak             Slovenia        GK       91   28   
4         Kevin De Bruyne               elgium    CM,CAM       91   30   
...                   ...                  ...       ...      ...  ...   
17995      Ulrik Mathisen               Norway        CM       52   22   
17996     Damian Tsekenis           Australia         ST       52   20   
17997  Abdullah Al Radeef        Saudi Arabia         ST       52   18   
17998       Aaron McNally  Republic of Ireland  RB,RM,LM       52   21   
17999      Lucas Forsberg               Sweden     RB,LB       52   18   

       potential                    team  
0             93     Paris Saint-Germain  
1             92          Bayern München  
2             95     Paris Saint-Germain  
3             93      Atlético de Madrid  
4             91         Manchester City  
...          ...                     ...  
17995         62           Lillestrøm SK  
17996         67  Central Coast Mariners  
17997         70                Al Hilal  
17998         66           Longford Town  
17999         66                     AIK  

[18000 rows x 7 columns]

# 포지션 별 유사도 측정

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
data['position']

0        ST,CF,RW
1              ST
2           ST,LW
3              GK
4          CM,CAM
           ...   
17995          CM
17996          ST
17997          ST
17998    RB,RM,LM
17999       RB,LB
Name: position, Length: 18000, dtype: object

In [9]:
# CountVectorizer를 적용하기 위해 공백문자로 word 단위가 구분되는 문자열로 변환. 
data['position'] = data['position'].apply(lambda x : x.replace(',',' '))
data

name          nationality  position  overall  age  \
0            Lionel Messi            Argentina  ST CF RW       93   34   
1      Robert Lewandowski               Poland        ST       92   33   
2           Kylian Mbappé               France     ST LW       91   22   
3               Jan Oblak             Slovenia        GK       91   28   
4         Kevin De Bruyne               elgium    CM CAM       91   30   
...                   ...                  ...       ...      ...  ...   
17995      Ulrik Mathisen               Norway        CM       52   22   
17996     Damian Tsekenis           Australia         ST       52   20   
17997  Abdullah Al Radeef        Saudi Arabia         ST       52   18   
17998       Aaron McNally  Republic of Ireland  RB RM LM       52   21   
17999      Lucas Forsberg               Sweden     RB LB       52   18   

       potential                    team  
0             93     Paris Saint-Germain  
1             92          Bayern München  
2             95     Paris Saint-Germain  
3             93      Atlético de Madrid  
4             91         Manchester City  
...          ...                     ...  
17995         62           Lillestrøm SK  
17996         67  Central Coast Mariners  
17997         70                Al Hilal  
17998         66           Longford Town  
17999         66                     AIK  

[18000 rows x 7 columns]

In [46]:
# CountVectorizer로 학습시켰더니 18000명 선수에 대한 279개 포지션의 '포지션 매트릭스'가 생성되었다.

count_vect = CountVectorizer(min_df=0, ngram_range=(1, 3))
position_mat = count_vect.fit_transform(data['position'])
print(position_mat.shape)
print(position_mat)

(18000, 279)
  (0, 231)	1
  (0, 43)	1
  (0, 191)	1
  (0, 240)	1
  (0, 45)	1
  (0, 242)	1
  (1, 231)	1
  (2, 231)	1
  (2, 106)	1
  (2, 259)	1
  (3, 56)	1
  (4, 47)	1
  (4, 0)	1
  (4, 48)	1
  (5, 106)	1
  (5, 0)	1
  (5, 4)	1
  (6, 231)	1
  (6, 106)	1
  (6, 259)	1
  (7, 231)	1
  (8, 56)	1
  (9, 56)	1
  (10, 130)	1
  (10, 26)	1
  :	:
  (17982, 106)	1
  (17983, 7)	1
  (17984, 56)	1
  (17985, 56)	1
  (17986, 0)	1
  (17987, 0)	1
  (17988, 57)	1
  (17989, 56)	1
  (17990, 7)	1
  (17991, 47)	1
  (17992, 231)	1
  (17993, 47)	1
  (17994, 7)	1
  (17995, 47)	1
  (17996, 231)	1
  (17997, 231)	1
  (17998, 130)	1
  (17998, 170)	1
  (17998, 91)	1
  (17998, 182)	1
  (17998, 162)	1
  (17998, 166)	1
  (17999, 130)	1
  (17999, 57)	1
  (17999, 147)	1


In [47]:
count_vect.vocabulary_

{'st': 231,
 'cf': 43,
 'rw': 191,
 'st cf': 240,
 'cf rw': 45,
 'st cf rw': 242,
 'lw': 106,
 'st lw': 259,
 'gk': 56,
 'cm': 47,
 'cam': 0,
 'cm cam': 48,
 'cam lw': 4,
 'rb': 130,
 'cdm': 26,
 'rb cdm': 139,
 'cb': 7,
 'rw lw': 192,
 'rm': 170,
 'lm': 91,
 'rm lm': 182,
 'lm cf': 96,
 'rm lm cf': 184,
 'cb cdm': 9,
 'cdm cm': 28,
 'cb cdm cm': 10,
 'lb': 57,
 'cam cf': 1,
 'rm cam': 171,
 'cam rw': 5,
 'rm cam rw': 174,
 'st rm': 266,
 'rm cm': 177,
 'st rm cm': 269,
 'lm lw': 103,
 'rm lm lw': 186,
 'rb lb': 147,
 'rm rw': 189,
 'st rm rw': 272,
 'cf lw': 44,
 'lb lm': 73,
 'st lm': 253,
 'cdm cm cam': 29,
 'cam cf lw': 2,
 'st rw': 273,
 'st rw lw': 274,
 'st lm lw': 257,
 'cm cam cf': 49,
 'cm cam lw': 50,
 'st rm cam': 267,
 'rb rm': 162,
 'lwb': 107,
 'lwb lm': 117,
 'lwb lm lw': 121,
 'lm cam': 92,
 'lm cam lw': 94,
 'rwb': 193,
 'rwb rb': 215,
 'rwb rb rm': 222,
 'rb rm rw': 167,
 'st cam': 232,
 'st cam cf': 233,
 'rm rw lw': 190,
 'cm cam rw': 51,
 'lb lwb': 79,
 'lb lwb lm

# 코사인 유사도(cosine_similarity)이용해서 포지션별 유사도 계산

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

position_cos_sim = cosine_similarity(position_mat, position_mat)

print(position_cos_sim.shape)
print(position_cos_sim[:10])

(18000, 18000)
[[1.         0.40824829 0.23570226 ... 0.40824829 0.         0.        ]
 [0.40824829 1.         0.57735027 ... 1.         0.         0.        ]
 [0.23570226 0.57735027 1.         ... 0.57735027 0.         0.        ]
 ...
 [0.40824829 1.         0.57735027 ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [49]:
# 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort
position_cos_sim_sorted_ind = position_cos_sim.argsort()[:, ::-1]
print(position_cos_sim_sorted_ind[:5])

[[    0  7080 12329 ... 11168 11167  8999]
 [10901 10590  1150 ... 11425 11424  8999]
 [ 6495  7446   706 ... 11243 11241  8999]
 [10431  2245 15312 ... 11480 11479     0]
 [ 1175  5849  5744 ... 11118 11117     0]]


# 추천 ver1. 포지션 코사인 유사도에 의해 포지션을 추천하는 함수

In [50]:
player_name = data[data['name'] == 'Kevin De Bruyne']
player_name

name nationality position  overall  age  potential  \
4  Kevin De Bruyne      elgium   CM CAM       91   30         91   

              team  new_rating  
4  Manchester City   82.564721

In [51]:
player_index = player_name.index.values
player_index

array([4], dtype=int64)

In [52]:
similar_indexes = position_cos_sim_sorted_ind[player_index, :10]
similar_indexes

array([[ 1175,  5849,  5744, 10155, 12758,  5783, 10117,  3899,  3894,
          288]], dtype=int64)

In [53]:
similar_indexes = similar_indexes.reshape(-1)
print(similar_indexes)

[ 1175  5849  5744 10155 12758  5783 10117  3899  3894   288]


In [54]:
data.iloc[similar_indexes]

name    nationality position  overall  age  potential  \
1175       Nicolás Filhei         Brazil   CM CAM       76   25         76   
5849          Josh Onomah        England   CM CAM       69   24         76   
5744     Bruno Fagundeiro         Brazil   CM CAM       69   21         69   
10155       Lucas Lingman        Finland   CM CAM       65   23         74   
12758       Franco Ragusa          Chile   CM CAM       63   28         63   
5783      Stijn Spierings    Netherlands   CM CAM       69   25         73   
10117      Christián Herc       Slovakia   CM CAM       65   23         74   
3899          Joel Soñora  United States   CM CAM       71   25         76   
3894   Morgan Gibbs-White        England   CM CAM       71   21         81   
288      Giovani Lo Celso      Argentina   CM CAM       81   25         85   

                          team  new_rating  
1175                 São Paulo   73.769380  
5849                    Fulham   73.655406  
5744                    Cuiabá   70.129859  
10155             HJK Helsinki   72.607449  
12758                 Cobresal   67.296112  
5783               Toulouse FC   72.144457  
10117  Grasshopper Club Zürich   72.607449  
3899                  Banfield   73.689141  
3894          Sheffield United   76.243098  
288          Tottenham Hotspur   78.736850

### 함수화

In [55]:
def find_sim_player_ver1(df, sorted_ind, player_name, top_n=10):
    
    player_name = df[df['name'] == player_name]
    
    player_index = player_name.index.values
    similar_indexes = sorted_ind[player_index, :(top_n)]
    
    print(similar_indexes)    
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

In [56]:
similar_player = find_sim_player_ver1(data, position_cos_sim_sorted_ind, 'Jan Oblak', 10)
similar_player

[[10431  2245 15312 15311 15309 15308 15303 15299 15296 12590]]


name       nationality position  overall  age  potential  \
10431  Thomas Mikkelsen           Denmark       GK       65   38         65   
2245    Frederik Rønnow           Denmark       GK       74   29         74   
15312         Adam Wilk            Poland       GK       60   23         67   
15311       Tim Wiesner           Germany       GK       60   24         67   
15309      Lewis Thomas             Wales       GK       60   24         66   
15308     Miguel Vargas             Chile       GK       60   25         66   
15303     Ameen Bukhari     Saudi Arabia        GK       60   24         68   
15299    Antoine Lejoly            elgium       GK       60   23         67   
15296       Dean Lyness           England       GK       60   30         60   
12590        Koki Otani            Japan        GK       63   32         63   

                             team  new_rating  
10431                  Brøndby IF   68.208952  
2245           1. FC Union Berlin   72.695709  
15312                    Cracovia   69.271802  
15311               VfL Osnabrück   69.271802  
15309         Forest Green Rovers   68.803052  
15308             Unión La Calera   68.803052  
15303                    Al Nassr   69.740552  
15299                   Beerschot   69.271802  
15296                  St. Mirren   65.990552  
12590  Hokkaido Consadole Sapporo   67.296112

In [57]:
data[data['position'] == 'GK'].sort_values(by = 'potential' , ascending=False).head(20)

name  nationality position  overall  age  potential  \
3                Jan Oblak     Slovenia       GK       91   28         93   
8     Gianluigi Donnarumma        Italy       GK       89   22         93   
11                 Ederson       Brazil       GK       89   28         91   
15        Thibaut Courtois       elgium       GK       89   29         91   
9                  Alisson       Brazil       GK       89   28         90   
97            Mike Maignan       France       GK       84   26         89   
19            Keylor Navas   Costa Rica       GK       88   34         88   
379         Dean Henderson      England       GK       80   24         87   
33       Wojciech Szczesny       Poland       GK       87   31         87   
36             Hugo Lloris       France       GK       87   34         87   
51           Koen Casteels       elgium       GK       86   29         87   
218      Pierluigi Gollini        Italy       GK       82   26         87   
182      Dominik Livakovic      Croatia       GK       82   26         87   
3807   Maarten Vandevoordt       elgium       GK       71   19         87   
530             Alex Meret        Italy       GK       79   24         86   
670          Justin Bijlow  Netherlands       GK       78   23         86   
57        Samir Handanovic     Slovenia       GK       86   37         86   
196             Unai Simón        Spain       GK       82   24         86   
843          Illan Meslier       France       GK       77   21         85   
3020       Lautaro Morales    Argentina       GK       72   21         85   

                         team  new_rating  
3          Atlético de Madrid   83.709375  
8         Paris Saint-Germain   83.591023  
11            Manchester City   82.457265  
15                Real Madrid   82.457265  
9                   Liverpool   81.890386  
97                      Milan   81.070991  
19        Paris Saint-Germain   80.710197  
379         Manchester United   79.775613  
33                   Juventus   80.101875  
36          Tottenham Hotspur   80.101875  
51              VfL Wolfsburg   80.057082  
218         Tottenham Hotspur   79.871938  
182             Dinamo Zagreb   79.871938  
3807                     Genk   79.307847  
530                    Napoli   79.189052  
670                 Feyenoord   79.142402  
57                      Inter   79.498641  
196   Athletic Club de Bilbao   79.325271  
843              Leeds United   78.564074  
3020                    Lanús   78.334219

# 가중평점(평점&평가횟수) 반영한 선수 추천

In [58]:
#고정
C = data['potential'].mean()
m = data['overall'].quantile(0.6)

def new_rating(record):
    v = record['overall']
    R = record['potential']
    
    return ( (v/(v+m)) * R ) + ( (m/(m+v)) * C )

In [59]:
data['new_rating'] = data.apply(new_rating, axis=1)

In [60]:
data

name          nationality  position  overall  age  \
0            Lionel Messi            Argentina  ST CF RW       93   34   
1      Robert Lewandowski               Poland        ST       92   33   
2           Kylian Mbappé               France     ST LW       91   22   
3               Jan Oblak             Slovenia        GK       91   28   
4         Kevin De Bruyne               elgium    CM CAM       91   30   
...                   ...                  ...       ...      ...  ...   
17995      Ulrik Mathisen               Norway        CM       52   22   
17996     Damian Tsekenis           Australia         ST       52   20   
17997  Abdullah Al Radeef        Saudi Arabia         ST       52   18   
17998       Aaron McNally  Republic of Ireland  RB RM LM       52   21   
17999      Lucas Forsberg               Sweden     RB LB       52   18   

       potential                    team  new_rating  
0             93     Paris Saint-Germain   83.824787  
1             92          Bayern München   83.192442  
2             95     Paris Saint-Germain   84.854029  
3             93      Atlético de Madrid   83.709375  
4             91         Manchester City   82.564721  
...          ...                     ...         ...  
17995         62           Lillestrøm SK   67.256589  
17996         67  Central Coast Mariners   69.423256  
17997         70                Al Hilal   70.723256  
17998         66           Longford Town   68.989922  
17999         66                     AIK   68.989922  

[18000 rows x 8 columns]

## 추천 ver2. 먼저 포지션 유사성 높은 선수 20개 선정 후(F1), 가중평점순 10개 선정(F2)

In [61]:
def find_sim_player_ver2(df, sorted_ind, player_name, top_n=10):
    player_name = df[df['name'] == player_name]
    player_index = player_name.index.values
    
    similar_indexes = sorted_ind[player_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)

    # 기준 선수 index는 제외
    similar_indexes = similar_indexes[similar_indexes != player_index]
    
    return df.iloc[similar_indexes].sort_values('new_rating', ascending=False)[:top_n]

In [62]:
position_cos_sim_sorted_ind

array([[    0,  7080, 12329, ..., 11168, 11167,  8999],
       [10901, 10590,  1150, ..., 11425, 11424,  8999],
       [ 6495,  7446,   706, ..., 11243, 11241,  8999],
       ...,
       [10901, 10590,  1150, ..., 11425, 11424,  8999],
       [13531,  8715, 10296, ..., 11130, 11129,     0],
       [17999, 13563,  8501, ..., 11370, 11369,     0]], dtype=int64)

In [63]:
similar_player = find_sim_player_ver2(data, position_cos_sim_sorted_ind, 'Kevin De Bruyne', 15)
similar_player

name      nationality position  overall  age  potential  \
633          Florian Wirtz          Germany   CM CAM       78   18         89   
288       Giovani Lo Celso        Argentina   CM CAM       81   25         85   
276          Lucas Paquetá           Brazil   CM CAM       81   24         85   
3837   Hamed Junior Traorè     Ivory Coast    CM CAM       71   21         84   
1485           Joe Willock          England   CM CAM       75   22         83   
3894    Morgan Gibbs-White          England   CM CAM       71   21         81   
632                Iniesta            Spain   CM CAM       79   37         79   
621       Gylfi Sigur?sson          Iceland   CM CAM       79   32         79   
3859           Dani de Wit      Netherlands   CM CAM       71   23         77   
1175        Nicolás Filhei           Brazil   CM CAM       76   25         76   
3899           Joel Soñora    United States   CM CAM       71   25         76   
5849           Josh Onomah          England   CM CAM       69   24         76   
10082  Francesco Antonucci           elgium   CM CAM       65   22         76   
9966        Julien Ponceau           France   CM CAM       65   20         75   
9968    Tobias Christensen           Norway   CM CAM       65   21         75   

                      team  new_rating  
633    Bayer 04 Leverkusen   80.745142  
288      Tottenham Hotspur   78.736850  
276     Olympique Lyonnais   78.736850  
3837              Sassuolo   77.775472  
1485      Newcastle United   77.425110  
3894      Sheffield United   76.243098  
632            Vissel Kobe   75.427147  
621                Everton   75.427147  
3859                    AZ   74.199933  
1175             São Paulo   73.769380  
3899              Banfield   73.689141  
5849                Fulham   73.655406  
10082            Feyenoord   73.584892  
9966       Nîmes Olympique   73.096170  
9968     Vålerenga Fotball   73.096170